dev

diff --git a/buckw b/buckw
--- a/buckw
+++ b/buckw
@@ -4,11 +4,11 @@
 ##
 ##  Buck wrapper script to invoke okbuck when needed, before running buck
 ##
-##  Created by OkBuck Gradle Plugin on : Sun Apr 23 23:36:50 BRT 2017
+##  Created by OkBuck Gradle Plugin on : Mon Aug 21 23:23:51 BRT 2017
 ##
 #########################################################################
 
-WORKING_DIR=$(pwd)
+WORKING_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 red=`tput setab 1 2>/dev/null || true`
 yellow=`tput setab 3 2>/dev/null || true`
@@ -148,7 +148,7 @@ setupBuckBinary ( ) {
         # Install buck from source if not already available
         if [[ ! -d "$BUCK_HOME" ]]; then
             warn "BUCK NOT FOUND IN '$BUCK_HOME'. INSTALLING BUCK..."
-            git clone $DEFAULT_BUCK_REPO $BUCK_HOME
+            git clone $DEFAULT_BUCK_REPO $BUCK_HOME || die "FAILED TO CLONE $DEFAULT_BUCK_REPO"
         fi
 
         # Add custom buck remote
@@ -156,9 +156,29 @@ setupBuckBinary ( ) {
             cd $BUCK_HOME
             REMOTE_EXISTS=$(git remote -v | grep "$CUSTOM_REMOTE_NAME")
             if [[ -z "$REMOTE_EXISTS" ]]; then
-                git remote add $CUSTOM_REMOTE_NAME $CUSTOM_BUCK_REPO
+                git remote add $CUSTOM_REMOTE_NAME $CUSTOM_BUCK_REPO || die "FAILED TO ADD REMOTE $CUSTOM_BUCK_REPO"
             fi
             cd -
+        fi
+
+        # Check for current buck version
+        BUCK_VERSION=$(cat $WORKING_DIR/.buckversion)
+        if [[ ! -z "$BUCK_VERSION" ]]; then
+            pushd "$BUCK_HOME" >/dev/null
+            CURRENT_BUCK_VERSION=$(git rev-parse HEAD)
+            if [[ "$BUCK_VERSION" != "$CURRENT_BUCK_VERSION" ]]; then
+                info "BUCK VERSION IS AT $CURRENT_BUCK_VERSION , BUT IT SHOULD BE $BUCK_VERSION. UPDATING BUCK"
+                git clean -fdx --quiet && git reset --hard --quiet && git fetch --all && git checkout "$BUCK_VERSION" --quiet && success "UPDATED BUCK TO $BUCK_VERSION" || die "FAILED TO UPDATE BUCK TO $BUCK_VERSION"
+            fi
+            popd >/dev/null
+        fi
+
+        # Build buck if needed
+        if [[ ! -f "$BUCK_HOME/build/successful-build" ]]; then
+            echo "Buck does not appear to have been built -- building Buck!"
+            pushd "$BUCK_HOME" >/dev/null
+            mkdir -p build && ant > build/ant.log && success "BUCK BUILT SUCCESSFULLY" || die "FAILED TO BUILD BUCK"
+            popd >/dev/null
         fi
 
         BUCK_BINARY="$BUCK_HOME/bin/buck"
@@ -190,6 +210,15 @@ setupBuckRun ( ) {
     setupBuckBinary
 }
 
+# Handle parameters and flags
+handleParams ( ) {
+   # Go directly to the kill command, help command, or --help option. Do not run okbuck.
+   if [[ "kill" == $1 || "help" == $1 || $@ == *"--help"* || $@ == *"-h"* ]]; then
+      SKIP_OKBUCK=true
+   fi
+}
+
+handleParams "$@"
 setupBuckRun
 
 # Invoke buck binary with arguments
